### ISSUE TITLE
Searching is slow

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#15]
Tag searches feel really slow right now. It can take anywhere from 3 to 10 seconds to perform a search. The amount of posts associated with the tag looks irrelevant as far as I can tell. Meanwhile, a tag search on yande.re seems to take less than a second.

Any ideas for the cause?

**Comment by vesta42** [comment]
Not sure why.

It could possibly be that some of the indexes were not restored after screwing with the tables for Unicode.

You can run the SQL statement `SHOW CREATE TABLE tags \G;` and in the output you should see:
```
PRIMARY KEY (`id`),
UNIQUE KEY `name` (`name`)
```
and `SHOW CREATE TABLE posts_tags \G;` and in the output you should see:
```
UNIQUE KEY `post_id` (`post_id`,`tag_id`),
KEY `fk_posts_tags__post_id` (`post_id`),
KEY `fk_posts_tags__tag_id` (`tag_id`),
CONSTRAINT `fk_posts_tags__post_id` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
CONSTRAINT `fk_posts_tags__tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE
```

If any of those lines are missing then that could be the problem. Otherwise, I don't know.

**Comment by Ma-ryan** [comment]
```
SHOW CREATE TABLE posts_tags \G;
*************************** 1. row ***************************
       Table: posts_tags
Create Table: CREATE TABLE `posts_tags` (
  `post_id` int(11) NOT NULL,
  `tag_id` int(11) NOT NULL,
  UNIQUE KEY `post_id` (`post_id`,`tag_id`),
  CONSTRAINT `fk_posts_tags__post_id` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT
```
Looks like some are indeed missing.

**Comment by vesta42** [comment]
Run the following:
```
ALTER TABLE posts_tags ADD CONSTRAINT `fk_posts_tags__tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE;
```
If you get an error then there is likely a row in the table that references a nonexistant tag and it will need to be deleted and you will need to run the command again. You can find such problem rows using a query like this:
```
SELECT posts_tags.* FROM posts_tags LEFT JOIN tags ON tags.id = posts_tags.tag_id WHERE tags.id IS NULL;
```

Once that that works, then run the following:
```
ALTER TABLE posts_tags ADD INDEX `fk_posts_tags__post_id` (`post_id`);
```

Then run `SHOW CREATE TABLE posts_tags \G;` again and verify that you now have all the keys.

**Comment by Ma-ryan** [comment]
Thanks. This seems to have fixed it. Searching takes about a second now, sometimes less.
