### ISSUE TITLE
Reparenting removes all tags

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#21]
Clicking "make this post the parent" removes all tags from the post and the child posts, except for tags that are automatically added (highres, absurdres, etc).

Additionally, I notice that attempting to undo the changes from the history causes the post to become both the parent and child simultaneously.

**Comment by vesta42** [comment]
That seems incredibly annoying. You can comment out the `CONFIG()->on_commit_tags_hook($this);` line in models/Post/TagMethods.php to disable it until I figure this out.

**Comment by vesta42** [comment]
Moving the hook below metatag processing seems to fix this issue. The way that post tags are handled is so overly complicated. I don't really understand why MyImouto handles the tags as it does.
